#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the primitive defaults that Flet's Dart renderer supplies when a
# property is absent from the wire. The authoritative input is the vendored
# Flet package pinned by this template, not a hand-maintained Swift list.
#
# Flutter theme/widget defaults (colors, typography and component geometry)
# are deliberately not guessed here; RufletUI resolves those through
# FletThemeDefaults because they depend on brightness, Material version and
# target platform.

template_root = File.expand_path("..", __dir__)
flet_root = File.join(template_root, "flet_packages", "flet", "lib", "src")
registry_path = File.join(flet_root, "flet_core_extension.dart")
controls_root = File.join(flet_root, "controls")
output_path = File.join(
  template_root,
  "apple_packages", "ruflet_apple", "Sources", "RufletEngine",
  "FletControlDefaults.generated.swift"
)

abort "Missing vendored Flet registry: #{registry_path}" unless File.file?(registry_path)

class_sources = {}
Dir.glob(File.join(controls_root, "*.dart")).sort.each do |path|
  File.read(path).scan(/class\s+(\w+Control)\b/).flatten.each do |class_name|
    class_sources[class_name] = path
  end
end

# The registry is the source of truth for wire type -> Dart renderer. Adjacent
# case labels intentionally share a renderer and therefore share its defaults.
type_renderers = {}
pending_types = []
File.foreach(registry_path) do |line|
  if (match = line.match(/case\s+"([^"]+)":/))
    pending_types << match[1]
  elsif (match = line.match(/return\s+(\w+Control)\s*\(/))
    class_name = match[1]
    source = class_sources[class_name]
    pending_types.each { |type| type_renderers[type] = [source, class_name] if source }
    pending_types.clear
  elsif line.include?("default:")
    pending_types.clear
  end
end

def primitive(expression)
  value = expression.strip
  return [:bool, value] if %w[true false].include?(value)
  # Named Flutter constants belong to the theme/platform layer. For example,
  # kToolbarHeight is 56 in Material but the native iOS navigation bar is 44.
  return nil if value.match?(/\A(?:k[A-Z]|Theme|CupertinoTheme)/)
  return [:double, value] if value.match?(/\A-?\d+\.\d+\z/)
  return [:int, value] if value.match?(/\A-?\d+\z/)
  if (string_match = value.match(/\A["']([^"']*)["']\z/))
    return [:string, string_match[1]]
  end

  # Parser defaults such as CrossAxisAlignment.center and Clip.hardEdge are
  # represented by the same lowercase enum token Flet accepts on the wire.
  if (enum_match = value.match(/\A[A-Z]\w*(?:<[^>]+>)?\.(\w+)\z/))
    return [:string, enum_match[1]]
  end

  nil
end

def swift_literal(kind, value)
  case kind
  when :bool then ".bool(#{value})"
  when :int then ".int(#{value})"
  when :double then ".double(#{value})"
  when :string
    escaped = value.gsub("\\", "\\\\").gsub('"', '\\"')
    ".string(\"#{escaped}\")"
  end
end

defaults = Hash.new { |hash, key| hash[key] = {} }

# Defaults applied by Flet around every control rather than one widget.
defaults["*"] = {
  "disabled" => [:bool, "false"],
  "expand_loose" => [:bool, "false"],
  "opacity" => [:double, "1.0"],
  "rtl" => [:bool, "false"],
  "visible" => [:bool, "true"]
}

type_renderers.each do |type, (source, class_name)|
  next unless source

  source_text = File.read(source)
  class_starts = source_text.enum_for(:scan, /^class\s+(\w+)/).map do
    [Regexp.last_match.begin(0), Regexp.last_match(1)]
  end
  dart = class_starts.each_with_index.filter_map do |(start, name), index|
    state_name = "_#{class_name.sub(/Control\z/, "ControlState")}"
    next unless name == class_name || name == state_name

    finish = class_starts[index + 1]&.first || source_text.length
    source_text[start...finish]
  end.join("\n")

  # Literal getters are Flet's explicit pre-constructor defaults.
  dart.scan(
    /(?:control|widget\.control)\.(get(?:Bool|Double|Int|String|MainAxisAlignment|CrossAxisAlignment|WrapAlignment|WrapCrossAlignment|ClipBehavior|Alignment))\(\s*"([^"]+)"\s*,\s*([^,\)\n]+)/m
  ).each do |_getter, property, expression|
    parsed = primitive(expression)
    defaults[type][property] = parsed if parsed
  end

  # Some Flet controls use a free parser around getString instead of a Control
  # extension, e.g. parseClip(control.getString(...), Clip.hardEdge).
  dart.scan(
    /parse\w+\(\s*(?:control|widget\.control)\.getString\(\s*"([^"]+)"\s*\)\s*,\s*([A-Z]\w*(?:<[^>]+>)?\.\w+)/m
  ).each do |property, expression|
    parsed = primitive(expression)
    defaults[type][property] = parsed if parsed
  end
end

aliases = {
  # Ruflet keeps Flet's historical names on the wire for compatibility while
  # the pinned Dart client funnels these through its unified Button renderer.
  "ElevatedButton" => "Button"
}

lines = []
lines << "// Generated by tool/generate_flet_defaults.rb. Do not edit."
lines << "// Source: vendored Flet ref 67a9763da3bd2611bbb7626c3a1ec5e9d30fc965."
lines << "import RufletProtocol"
lines << ""
lines << "public enum FletControlDefaults {"
lines << "  private static let aliases: [String: String] = ["
aliases.sort.each { |from, to| lines << "    \"#{from}\": \"#{to}\"," }
lines << "  ]"
lines << ""
lines << "  private static let values: [String: [String: RufletValue]] = ["
defaults.keys.sort.each do |type|
  properties = defaults[type]
  next if properties.empty?

  lines << "    \"#{type}\": ["
  properties.keys.sort.each do |property|
    kind, value = properties[property]
    lines << "      \"#{property}\": #{swift_literal(kind, value)},"
  end
  lines << "    ],"
end
lines << "  ]"
lines << ""
lines << "  public static func value(for controlType: String, property: String) -> RufletValue? {"
lines << "    let canonicalType = aliases[controlType] ?? controlType"
lines << "    return values[canonicalType]?[property] ?? values[\"*\"]?[property]"
lines << "  }"
lines << "}"
lines << ""

File.write(output_path, lines.join("\n"))
puts "Generated #{output_path.sub(template_root + "/", "")} (#{defaults.size - 1} controls)"
