#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the primitive property resolver consumed by ControlNode. Its sole
# semantic input is the versioned Flet contract generated from the vendored
# Flet registries and renderer sources; Swift does not maintain a second list.

require "json"

template_root = File.expand_path("..", __dir__)
contract_path = File.join(template_root, "tool", "conformance", "flet_control_contract.json")
output_path = File.join(
  template_root, "apple_packages", "ruflet_apple", "Sources", "RufletEngine",
  "FletControlDefaults.generated.swift"
)

abort "Missing generated Flet contract: #{contract_path}" unless File.file?(contract_path)
contract = JSON.parse(File.read(contract_path))

def swift_literal(default)
  value = default.fetch("value")
  case default.fetch("type")
  when "bool" then ".bool(#{value})"
  when "int" then ".int(#{value})"
  when "double" then ".double(#{value.to_f})"
  when "string", "enum"
    escaped = value.gsub("\\", "\\\\").gsub('"', '\\"')
    ".string(\"#{escaped}\")"
  else
    abort "Unsupported primitive default type: #{default.inspect}"
  end
end

defaults = contract.fetch("controls").to_h do |control|
  [control.fetch("wire_type"), control.fetch("primitive_defaults")]
end
defaults["*"] = contract.fetch("global_primitive_defaults")

# These foundational controls are the native layout contract. Abort generation
# if upstream extraction regresses instead of silently restoring literals in a
# Swift view and drifting from Flet again.
required = {
  "Page" => %w[title],
  "View" => %w[can_pop horizontal_alignment spacing vertical_alignment],
  "AppBar" => %w[automatically_imply_leading],
  "Row" => %w[alignment spacing tight vertical_alignment],
  "Column" => %w[alignment horizontal_alignment spacing tight],
  "Container" => %w[ignore_interactions ink]
}
required.each do |control, properties|
  missing = properties - defaults.fetch(control, {}).keys
  abort "Flet contract lost #{control} defaults: #{missing.join(', ')}" unless missing.empty?
end

aliases = { "ElevatedButton" => "Button" }
source = contract.fetch("source")
lines = []
lines << "// Generated by tool/generate_flet_defaults.rb. Do not edit."
lines << "// Source: Flet #{source.fetch('flet_version')} ref #{source.fetch('flet_ref')}."
lines << "import RufletProtocol"
lines << ""
lines << "public enum FletControlDefaults {"
lines << "  private static let aliases: [String: String] = ["
aliases.sort.each { |from, to| lines << "    \"#{from}\": \"#{to}\"," }
lines << "  ]"
lines << ""
lines << "  private static let values: [String: [String: RufletValue]] = ["
defaults.keys.sort.each do |type|
  properties = defaults.fetch(type)
  next if properties.empty?

  lines << "    \"#{type}\": ["
  properties.keys.sort.each do |property|
    lines << "      \"#{property}\": #{swift_literal(properties.fetch(property))},"
  end
  lines << "    ],"
end
lines << "  ]"
lines << ""
lines << "  public static func value(for controlType: String, property: String) -> RufletValue? {"
lines << "    let canonicalType = aliases[controlType] ?? controlType"
lines << "    return values[canonicalType]?[property] ?? values[\"*\"]?[property]"
lines << "  }"
lines << "}"
lines << ""

generated = lines.join("\n")
if ARGV.delete("--check")
  current = File.file?(output_path) ? File.read(output_path) : nil
  abort "Generated Flet defaults are stale. Run #{__FILE__}." unless current == generated
  puts "Generated Flet defaults are current."
else
  File.write(output_path, generated)
  puts "Generated #{output_path.sub(template_root + '/', '')} (#{defaults.size - 1} controls)"
end
