#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the Ruflet wire-icon index -> Flutter Material Icons font
# codepoint table. Ruflet serializes an index from its icons.json catalog,
# while Flutter's Icons class stores the actual glyph codepoint. Both catalogs
# must stay in exact lockstep or the generated Apple renderer would draw the
# wrong glyph.
#
# Usage:
#   ruby tool/generate_material_icon_glyphs.rb --flutter-root /path/to/flutter

require "optparse"

root = File.expand_path("..", __dir__)
flutter_root = ENV["FLUTTER_ROOT"]
OptionParser.new do |options|
  options.on("--flutter-root PATH") { |value| flutter_root = value }
end.parse!
abort "Pass --flutter-root or set FLUTTER_ROOT" if flutter_root.to_s.empty?

names_source = File.join(root, "Sources/RufletUI/Support/MaterialIconNames.swift")
icons_source = File.join(flutter_root, "packages/flutter/lib/src/material/icons.dart")
output = File.join(root, "Sources/RufletUI/Support/MaterialIconGlyphs.generated.swift")

abort "Missing #{names_source}" unless File.file?(names_source)
abort "Missing #{icons_source}" unless File.file?(icons_source)

names_body = File.read(names_source).match(
  /private static let materialTable = """\n(.*?)\n"""/m
)&.captures&.first
abort "Could not read MaterialIconNames.materialTable" unless names_body
names = names_body.lines(chomp: true)

icons = {}
File.read(icons_source).scan(
  /static const IconData\s+(\w+)\s*=\s*IconData\((.*?)\);/m
) do |name, constructor|
  codepoint = constructor.match(/\A\s*0x([0-9a-fA-F]+)/)&.captures&.first
  next unless codepoint && constructor.include?("fontFamily: 'MaterialIcons'")
  icons[name] = {
    codepoint: codepoint.downcase,
    match_text_direction: constructor.include?("matchTextDirection: true")
  }
end

missing = names.reject { |name| icons.key?(name.downcase) }
abort "Flutter is missing #{missing.length} Ruflet icons: #{missing.first(20).join(', ')}" unless missing.empty?
abort "Expected #{names.length} distinct Flutter icons, found #{icons.length}" unless names.length == icons.length

lines = []
lines << "// Generated by tool/generate_material_icon_glyphs.rb -- do not edit by hand."
lines << "// Source: Flutter packages/flutter/lib/src/material/icons.dart."
lines << ""
lines << "import Foundation"
lines << ""
lines << "enum MaterialIconGlyphs {"
lines << "  static let fontFamily = \"Material Icons\""
lines << "  static let postScriptName = \"MaterialIcons-Regular\""
lines << "  static let codepoints: [Int] = codepointTable.split(separator: \"\\n\").compactMap {"
lines << "    Int($0, radix: 16)"
lines << "  }"
lines << "  static let textDirectionMatchingNames: Set<String> = Set("
lines << "    textDirectionMatchingTable.split(separator: \"\\n\").map(String.init))"
lines << ""
lines << "  static func codepoint(forName rawName: String) -> Int? {"
lines << "    let canonical = rawName.uppercased().replacingOccurrences(of: \"-\", with: \"_\")"
lines << "    guard let index = MaterialIconNames.material.firstIndex(of: canonical) else { return nil }"
lines << "    return codepoints[index]"
lines << "  }"
lines << ""
lines << "  static func codepoint(forWireCodepoint wireCodepoint: Int) -> Int? {"
lines << "    let index = wireCodepoint - MaterialIconNames.firstCodepoint"
lines << "    guard codepoints.indices.contains(index) else { return nil }"
lines << "    return codepoints[index]"
lines << "  }"
lines << ""
lines << "  static func matchesTextDirection(name: String) -> Bool {"
lines << "    textDirectionMatchingNames.contains(name.uppercased())"
lines << "  }"
lines << ""
lines << "  private static let codepointTable = \"\"\""
lines.concat(names.map { |name| icons.fetch(name.downcase).fetch(:codepoint) })
lines << "\"\"\""
lines << ""
lines << "  private static let textDirectionMatchingTable = \"\"\""
lines.concat(names.select { |name| icons.fetch(name.downcase).fetch(:match_text_direction) })
lines << "\"\"\""
lines << "}"
lines << ""

File.write(output, lines.join("\n"))
puts "Wrote #{names.length} Material glyph codepoints to #{output.sub("#{root}/", "")}"
